// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://lhsyxlfdzhpmxlndihqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxoc3l4bGZkemhwbXhsbmRpaHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MzMwNTAsImV4cCI6MjA1NzEwOTA1MH0.OETHuoUSlVID67bsoZgbjV2giOhNrS-Ou4C5JQMHpXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

