// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ontbsbhtyoruxofazyrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9udGJzYmh0eW9ydXhvZmF6eXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MjA2NTMsImV4cCI6MjA1NjI5NjY1M30.vSHr3jLOOg7Sd3C6F5gfxVPXMd5Orr5YM0k2jBO5WEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);